name: test
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Store/Restore Blender installation cache
        id: blender-cache
        uses: actions/cache@v4
        with:
          path: ./blender
          key: ${{ runner.os }}-blender-${{ hashFiles('./dev.py') }}
          restore-keys: |
            ${{ runner.os }}-blender-${{ hashFiles('./dev.py') }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Run tests
        run: python dev.py test
